### ISSUE TITLE
Dependences examples

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/parmesan#28]
How to make in yaml one o more dependences, before I can write: 

```
agg:
  show: true
  depends_on: 
    ftype:
      one_of: [CatNum, Cat]
    viz:
      one_of:[bar, pie]
  input_info:
    input_type: selectizeInput
```

**Comment by jpmarindiaz** [comment]
It should work like this (you can use `show_if`, `show_if_all`, `show_if_any`

See example 06
https://github.com/datasketch/parmesan/tree/master/inst/examples/ex06-conditions 

```
num_column:
  show: true
  show_if_all:
    num_or_fct:
      has: numeric
    enable_num_selector:
      equals: true
  input_type: selectInput
  input_params:
    label: "Select numeric column"
    choices: datasetNumCols()
    selected: 1
    multiple: true
```
