### ISSUE TITLE
Check if parmesan input parameters are ok

### ISSUE THREAD

**Issue by jpmarindiaz** [datasketch/parmesan#33]
Using `weird` as parameter should throw an informative error
```
  input_type: textInput
  input_params:
    label: Title
    weird: "My text"
```
