### ISSUE TITLE
If section is NULL (render_section) its should render all the sections writes in "layout"

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/parmesan#42]
My layout .yaml
```
titles:
  label: Titles
  inputs:
    - title
    - subtitle
    - caption
colors:
  label: Colors
  inputs:
    - palette_colors
```
inputs:

```
---
title:
  show: true
  input_type: textInput
  input_params:
    label: Title
    value:
subtitle:
  show: true
  input_type: textInput
  input_params:
    label: Subtitle
    value:
caption:
  show: true
  input_type: textInput
  input_params:
    label: caption
    value: 
palette_colors:
  show: true
  input_type: colorPaletteInput
  input_params:
    label: palette_colors
    colors:
    - "#FA0A0A"
    - "#4354A3"
    - "#3298A0"
    - "#563208"
    - "#cd5490"
    - "#5689c4"
```

In R (server):
```
library(shinypanels)
library(parmesan)
library(shi18ny)
library(shinyinvoer)

ui <- panelsPage(
  panel(title = "Options",
        color = "chardonnay",
        width = 350,
        body = uiOutput("controls"))
)

server <- function(input, output, session) {

  parmesan <- parmesan_load("parmesan")
  
  output$controls <- renderUI({
  #  render_section(parmesan = parmesan)
    render_section("all_controls_here", parmesan = parmesan)
  })
  
}
```

Result: 

![imagen](https://user-images.githubusercontent.com/17035597/83147355-2e0ba680-a0bd-11ea-9b19-560add8f1ecd.png)

colors section is ignored
