### ISSUE TITLE
The tooltip will must put in a section of yaml

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/parmesan#45]
por example
```
colors:
  label: colors
  section_info:
    icon: info-circle
    text: colors_info
  inputs:
    - palette_colors
    - background_color
summarize: 
```
