### ISSUE TITLE
text info tooltip should receive reactives

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/parmesan#49]
```
tooltip:
  show: true
  input_type: textInput
  input_params:
    label: tooltip
    value: 
  input_info:
    icon: info-circle
    text: tooltip_info()
```

tooltip_info() is ready as text and no the info into reactive
